print("Início")
print("Ler o valor de A")
print("Ler o valor de B")
print("Ler o valor de C")
print("Verificar se A < B + C e B < A + C e C < A + B")
print("Se não, imprimir 'Não é um triângulo' e ir para o fim")
print("Se sim, continuar")
print("Verificar se A = B e B = C")
print("Se sim, imprimir 'O triângulo é Equilátero' e ir para o fim")
print("Se não, verificar se A = B ou A = C ou B = C")
print("Se sim, imprimir 'O triângulo é Isósceles'")
print("Se não, imprimir 'O triângulo é Escaleno'")
print("Fim")
